-- 021_eden_seed.sql
-- Seed Eden For Your World as a real beta client.
-- Uses a deterministic UUID so we can reference it consistently.

INSERT INTO agents (
  id,
  full_name,
  agency_name,
  tagline,
  email,
  auth_user_id,
  phone,
  role,
  tier,
  subscription_status,
  template,
  onboarding_completed_at,
  bio,
  travel_specialties,
  destination_specialties,
  preferred_suppliers,
  travel_types,
  instagram_url,
  facebook_url,
  website_url
) VALUES (
  '2e18df43-171a-4565-b840-aade259cab69',
  'John Oberacker',
  'Eden For Your World',
  'Curating the world''s most extraordinary journeys — with precision, passion, and white-glove care.',
  'kasra@edenforyourworld.com',
  '2e18df43-171a-4565-b840-aade259cab69',
  '+1 (562) 856-8603',
  'agent',
  'growth',
  'active',
  'frontend',
  NOW(),
  'After two decades curating bespoke itineraries for executives, families, and discerning honeymooners, I founded Eden For Your World on a single belief: extraordinary travel begins with someone who has already been there, and knows the right person at the front desk. Every trip we craft is built around small, considered details — a private balcony breakfast in Positano, a midnight stargazing session in the Atacama, a sommelier waiting at the cellar door. We do not sell catalogues. We send you somewhere unforgettable, and we are on call from your first message to your last night.',
  ARRAY['Luxury', 'Honeymoons & Romance', 'Family', 'Wellness & Spa', 'Culinary & Wine', 'Cultural & Heritage'],
  ARRAY['Europe', 'Mediterranean', 'Caribbean', 'Asia-Pacific', 'Africa', 'South Pacific'],
  ARRAY['Virtuoso', 'Aman', 'Four Seasons', 'Belmond', 'Rosewood', 'Regent Seven Seas', 'Silversea'],
  ARRAY['Bespoke Itineraries', 'Cruises', 'Luxury Villas', 'All-Inclusive Resorts', 'Escorted Tours'],
  'https://www.instagram.com/edenforyourworld',
  'https://www.facebook.com/edenforyourworld',
  'https://www.edenforyourworld.com'
)
ON CONFLICT (email) DO UPDATE SET
  full_name              = EXCLUDED.full_name,
  agency_name            = EXCLUDED.agency_name,
  tagline                = EXCLUDED.tagline,
  auth_user_id           = EXCLUDED.auth_user_id,
  phone                  = EXCLUDED.phone,
  tier                   = EXCLUDED.tier,
  subscription_status    = EXCLUDED.subscription_status,
  template               = EXCLUDED.template,
  onboarding_completed_at = COALESCE(agents.onboarding_completed_at, EXCLUDED.onboarding_completed_at),
  bio                    = EXCLUDED.bio,
  travel_specialties     = EXCLUDED.travel_specialties,
  destination_specialties = EXCLUDED.destination_specialties,
  preferred_suppliers    = EXCLUDED.preferred_suppliers,
  travel_types           = EXCLUDED.travel_types,
  instagram_url          = EXCLUDED.instagram_url,
  facebook_url           = EXCLUDED.facebook_url,
  website_url            = EXCLUDED.website_url;
