-- Four Seasons Private Jet: content and imagery from the 2027/2028 brochures.
--
-- Photography is the Four Seasons / TCS World Travel brochure imagery dropped
-- into public/media/private-jets/four-seasons-private-jet/ (see the README
-- there for rights). Itinerary facts — dates, day counts, stops, published
-- per-person prices — come from the six travel-advisor brochures on file and,
-- for the three routings without a brochure (Asia Unveiled, Timeless
-- Encounters, Uncharted Discovery), from fourseasons.com/privatejet as read on
-- 2026-09-02. Ordered by departure date.
--
-- All literals are dollar-quoted so apostrophes are written once.

update public.private_journeys set
  hero_image_url = $q$/media/private-jets/four-seasons-private-jet/african-wonders/jet/jet-exterior-a321neo-runway-sunset.jpg$q$,
  slider_images = $q$[
    "/media/private-jets/four-seasons-private-jet/african-wonders/jet/cabin-italian-leather-flatbed-seats.jpg",
    "/media/private-jets/four-seasons-private-jet/african-wonders/jet/cabin-dining-beverage-service.jpg",
    "/media/private-jets/four-seasons-private-jet/international-intrigue/jet/inflight-wine-service.jpg",
    "/media/private-jets/four-seasons-private-jet/grand-horizons/jet/cabin-flatbed-seat-window.jpg",
    "/media/private-jets/four-seasons-private-jet/international-intrigue/jet/inflight-plated-meal-tray.jpg",
    "/media/private-jets/four-seasons-private-jet/ancient-explorer/jet/mixologist-preparing-drink.jpg",
    "/media/private-jets/four-seasons-private-jet/african-wonders/lifestyle/beach-firepit-gathering-mauritius.jpg",
    "/media/private-jets/four-seasons-private-jet/new-world-icons/anguilla/beach-dinner-sunset-palms.jpg"
  ]$q$::jsonb,
  description = $q$Nine itineraries run in 2027 and 2028: three around-the-world routings of 21 to 23 days, and regional journeys through Africa, Asia, the Americas and Antarctica. Published prices run from USD 167,000 to USD 252,000 per person, and several 2027 departures are already on waitlist.$q$,
  intro = $q${"eyebrow": "Private Aviation", "heading": "Around the world on one aircraft, with Four Seasons throughout.", "body": "Each journey flies a custom-configured Airbus A321neo-LR carrying 48 guests, staying at Four Seasons hotels and resorts, and at lodges and ships chosen by Four Seasons where there is no hotel. Flights, hotels, meals, excursions, ground transport, luggage handling and gratuities are all included. A Journey Concierge, Director of Guest Experience, Executive Chef and physician travel with the group from the first day to the last."}$q$::jsonb,
  destinations = $q$[
    {"name": "Africa & the Indian Ocean", "image_url": "/media/private-jets/four-seasons-private-jet/african-wonders/rwanda/mountain-gorilla-family.jpg", "blurb": "The Serengeti, Rwanda's mountain gorillas, Mauritius, the Seychelles, Marrakech and the Nile at Luxor, on African Wonders, International Intrigue and World of Adventures."},
    {"name": "Asia & the Pacific", "image_url": "/media/private-jets/four-seasons-private-jet/world-of-adventures/kyoto/fushimi-inari-torii-gates.jpg", "blurb": "Tokyo, Kyoto, Bangkok, Hoi An, Bali, Bhutan, the Maldives, Bora Bora and the Great Barrier Reef, reached on six of the nine routings."},
    {"name": "Europe & the Mediterranean", "image_url": "/media/private-jets/four-seasons-private-jet/ancient-explorer/taormina/san-domenico-terrace-sea-view.jpg", "blurb": "Milan, Venice, Geneva, Paris, Budapest, Prague, Istanbul, Mallorca, Taormina, Iceland and London, usually as the closing chapters of the around-the-world journeys."},
    {"name": "The Americas & Antarctica", "image_url": "/media/private-jets/four-seasons-private-jet/world-of-adventures/galapagos/bartolome-bay-pinnacle-rock.jpg", "blurb": "Los Angeles, Napa Valley, Seattle, Mexico City, Los Cabos, Anguilla, Bogotá and the Galápagos, plus Machu Picchu, Buenos Aires and a four-night Antarctic cruise on Uncharted Discovery."}
  ]$q$::jsonb,
  experiences = $q$[
    {"icon": "upgrade", "title": "Airbus A321neo-LR, 48 Seats", "description": "Configured by the Four Seasons design team. 48 flat-bed seats in Italian leather, each with 6.5 feet of personal space, in one of the tallest and widest cabins in its class."},
    {"icon": "breakfast", "title": "On-Board Executive Chef", "description": "The highest Four Seasons restaurant in the world. Menus change with the next destination, and the lounge keeps a rotating selection of food and drink between meals."},
    {"icon": "excursion", "title": "Journey Concierge", "description": "A Journey Concierge and Director of Guest Experience travel the full itinerary, adjusting plans in real time and arranging private or off-programme experiences."},
    {"icon": "default", "title": "Journey Physician", "description": "A doctor accompanies every departure, on the ground and in the air."},
    {"icon": "luggage", "title": "Room-to-Runway Luggage Service", "description": "A dedicated luggage concierge moves bags between suite and aircraft at every stop."},
    {"icon": "vip", "title": "Four Seasons-Trained Flight Crew", "description": "The cabin crew carry proprietary Four Seasons service training, so the standard in the air matches the hotels."}
  ]$q$::jsonb,
  sample_journeys = $q$[
    {"name": "Asia Unveiled", "dates": "February 11 to 26, 2027, and February 15 to March 2, 2028", "regions": "Asia & Pacific", "stops": ["Tokyo", "Bali", "Angkor Wat", "Hoi An", "Bhutan", "Maldives", "Bangkok"], "price_from_usd": 167000, "image_url": "/media/private-jets/four-seasons-private-jet/ancient-explorer/bangkok/grand-palace-wide.jpg", "blurb": "Seven destinations across Asia in 16 or 17 days: Tokyo's tuna auction, a day stop at Angkor Wat, Bhutan, the Maldives, and a Vespa food tour of Hoi An. The most accessibly priced routing in the programme. The 2027 departure has limited availability."},
    {"name": "Timeless Encounters", "dates": "April 15 to May 6, 2027", "days": 22, "regions": "Around the world", "stops": ["Kona", "Bora Bora", "Sydney", "Bali", "Chiang Mai or Chiang Rai", "Dubai", "Taj Mahal (optional day trip)", "Prague", "London"], "price_from_usd": 235000, "image_url": "/media/private-jets/four-seasons-private-jet/ancient-explorer/bora-bora/overwater-villa-deck-pool.jpg", "blurb": "The longest-running around-the-world routing: Kona, Bora Bora, Sydney, Bali, northern Thailand, Dubai with an optional day trip to the Taj Mahal, then Prague and London. The 2027 departure is on waitlist."},
    {"name": "World of Adventures", "dates": "August 10 to September 2, 2027", "days": 24, "regions": "Four continents", "stops": ["Seattle", "Kyoto", "Bali", "Seychelles", "Rwanda", "Marrakech", "Bogotá", "Galápagos Islands", "Los Angeles"], "price_from_usd": 239000, "image_url": "/media/private-jets/four-seasons-private-jet/world-of-adventures/bali/rice-terraces-palms-SPREAD.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/world-of-adventures-august-2027.pdf", "blurb": "Four continents in 24 days, built around wildlife: mountain gorillas in Rwanda, four nights aboard a private ship in the Galápagos, a sea turtle release in Bali, plus Kyoto, the Seychelles, Marrakech and Bogotá."},
    {"name": "Ancient Explorer", "dates": "September 3 to 25, 2027", "days": 23, "regions": "Around the world", "stops": ["Los Angeles", "Mexico City", "Easter Island", "Bora Bora", "Great Barrier Reef", "Bangkok", "Amman and Petra", "Taormina", "London"], "price_from_usd": 235000, "image_url": "/media/private-jets/four-seasons-private-jet/ancient-explorer/mexico-city/teotihuacan-balloons-SPREAD.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/ancient-explorer-september-2027.pdf", "blurb": "Nine destinations weighted to archaeology: hot-air balloons over Teotihuacan, the moai of Easter Island, the Great Barrier Reef, Petra, and Taormina under Mount Etna, opening in Los Angeles and closing in London."},
    {"name": "Uncharted Discovery", "dates": "January 24 to February 13, 2028", "days": 21, "regions": "The Americas & Antarctica", "stops": ["Los Angeles", "Tamarindo", "Machu Picchu", "Buenos Aires", "Antarctica", "Cartagena", "Puerto Rico"], "price_from_usd": 234000, "image_url": "/media/private-jets/four-seasons-private-jet/world-of-adventures/los-angeles/santa-monica-pier-dusk.jpg", "blurb": "The Americas to Antarctica: Machu Picchu by private train, a day trip by jet from Buenos Aires to Iguazú Falls, and a four-night polar cruise to the Antarctic Peninsula, with beach stays in Tamarindo and Puerto Rico. The 2027 departure is on waitlist."},
    {"name": "New World Icons", "dates": "March 1 to 20, 2028", "days": 20, "regions": "Asia, Europe & the Americas", "stops": ["Hong Kong", "Langkawi", "Jaipur", "Venice", "Iceland", "Anguilla", "Los Cabos"], "price_from_usd": 229000, "image_url": "/media/private-jets/four-seasons-private-jet/new-world-icons/langkawi/sky-bridge-jungle.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/new-world-icons-ta-28.pdf", "blurb": "Seven destinations, several new to the programme: Hong Kong, Langkawi, Rambagh Palace in Jaipur, Hotel Danieli in Venice with a helicopter day in the Dolomites, snowmobiling on Langjökull Glacier in Iceland, then Anguilla and Los Cabos."},
    {"name": "International Intrigue", "dates": "March 21 to April 10, 2028", "days": 21, "regions": "Around the world", "stops": ["Seattle", "Kyoto", "Hoi An", "Maldives", "Serengeti", "Marrakech", "Budapest", "Paris"], "price_from_usd": 249000, "image_url": "/media/private-jets/four-seasons-private-jet/international-intrigue/serengeti/acacia-sunset-bush-picnic.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/international-intrigue-2028-brochure-TA.pdf", "blurb": "The defining around-the-world routing: samurai training in Kyoto, The Nam Hai in Hoi An, Kuda Huraa in the Maldives, a balloon flight over the Serengeti, Marrakech, Budapest, and a farewell dinner at Le Cinq in Paris."},
    {"name": "Grand Horizons", "dates": "April 12 to May 4, 2028", "days": 23, "regions": "Around the world", "stops": ["Napa Valley", "Tokyo", "Ha Long Bay", "Bangkok or Koh Samui", "Istanbul", "Mallorca", "Geneva", "Milan"], "price_from_usd": 252000, "image_url": "/media/private-jets/four-seasons-private-jet/grand-horizons/milan/duomo-rooftop-city-view-SPREAD.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/Grand-Horizons-Brochure-2028-TA.pdf", "blurb": "The culinary circumnavigation: Napa Valley, Tokyo, two nights on a private ship in Ha Long Bay, Bangkok or Koh Samui, Istanbul, Mallorca, Geneva and Milan, with a backstage tour of La Scala and a private viewing of the Duomo."},
    {"name": "African Wonders", "dates": "August 18 to 31, 2028", "days": 14, "regions": "Africa", "stops": ["Athens", "Luxor", "Cairo", "Serengeti", "Mauritius", "Rwanda", "Johannesburg"], "price_from_usd": 199000, "image_url": "/media/private-jets/four-seasons-private-jet/african-wonders/luxor/karnak-temple-columns-ramesses-SPREAD.jpg", "brochure_url": "/media/private-jets/four-seasons-private-jet/African-Wonders-Brochure-2028-TA.pdf", "blurb": "The family departure: Athens, the Valley of the Kings and Karnak from the new Four Seasons Hotel Luxor, a day at Giza and the Grand Egyptian Museum, three nights each in the Serengeti and Mauritius, gorilla trekking in Rwanda, then Johannesburg. Child rates are published."}
  ]$q$::jsonb,
  price_from_usd = 167000,
  price_note = $q$Per person, double occupancy, as published by Four Seasons for 2027 and 2028 departures. Solo traveller supplements apply, and African Wonders publishes child rates from USD 170,000. Journeys are sold and operated by TCS World Travel; the aircraft is operated by Titan Airways.$q$
where slug = 'four-seasons-private-jet';
