-- 057_seed_private_journeys.sql
-- Seeds the three launch operators for /private-jets and /safaris.
--
-- Facts come from each operator's own site: the Airbus A321 configuration and
-- the nine named Four Seasons journeys; A&K's 1962 founding, its 3,000 staff
-- across 65 offices in 40 countries, and its five travel modes; Micato's
-- fourteen published itineraries with durations and per-person prices, and its
-- ten Travel+Leisure wins. Copy is written from those facts, not lifted.
--
-- hero_image_url / slider_images are intentionally absent: no licensed
-- photography for these brands is in the repo. T2JourneyDetail renders a
-- typographic hero and skips the gallery when they are missing, so the pages
-- read as finished rather than broken. See public/media/private-jets/README.md
-- for the drop zone and the one-statement wiring once assets land.
--
-- Four Seasons and A&K publish no pricing, so price_from_usd is null and the UI
-- shows "On request" rather than inventing a figure. Micato's figures carry a
-- price_note flagging them for verification before they are quoted.
--
-- All literals below are dollar-quoted, where an apostrophe is written once.
-- Writing '' inside a $tag$ block yields a literal doubled apostrophe, which is
-- how "East Africa''s" reached the first applied version of this seed.

insert into public.private_journeys
  (slug, name, journey_type, tagline, description, intro, destinations,
   experiences, sample_journeys, benefits, price_from_usd, price_note, sort_order)
values
(
  $q$four-seasons-private-jet$q$, $q$Four Seasons Private Jet$q$, $q$jet$q$,
  $q$The whole world, on one aircraft$q$,
  $q$Four Seasons Private Jet Journeys circle the globe aboard a fully customised Airbus A321, staying in Four Seasons hotels and resorts along the way. A dedicated journey team travels with the aircraft — concierge, executive chef, physician, and Four Seasons-trained cabin crew — so the standard on the ground and the standard at altitude are the same one.$q$,
  $q${"eyebrow": "Private Aviation", "heading": "One aircraft, one team, one continuous standard.", "body": "The aircraft is configured for a fraction of the passengers an A321 would normally carry. What that buys is space, but more importantly it buys pace: no connections, no terminals, no re-packing. Journeys are sold and operated by TCS World Travel; the aircraft is operated by Titan Airways."}$q$::jsonb,
  $q$[{"name": "Africa & the Indian Ocean", "blurb": "African Wonders traces the continent's great landscapes and the lodges that sit quietly inside them."}, {"name": "Asia", "blurb": "Asia Unveiled moves between the region's imperial cities and its quieter coastlines."}, {"name": "The Americas", "blurb": "New World Icons connects the landmarks of North and South America without a single scheduled flight."}, {"name": "Around the World", "blurb": "Grand Horizons and Timeless Encounters are the full circumnavigations — the format the jet was built for."}]$q$::jsonb,
  $q$[{"title": "24/7 Personal Concierge", "description": "On call for the length of the journey, on the ground and in the air."}, {"title": "On-Board Executive Chef", "description": "Menus built around where the aircraft has just been and where it is going next."}, {"title": "Journey Physician", "description": "A doctor travels with the group for every departure."}, {"title": "Dedicated Luggage Concierge", "description": "Bags move between aircraft and suite without passing through your hands."}, {"title": "Four Seasons-Trained Crew", "description": "The cabin is staffed to the standard of the hotels the journey stays in."}]$q$::jsonb,
  $q$[{"name": "Grand Horizons", "regions": "Around the world", "blurb": "The full circumnavigation — the flagship itinerary in the programme."}, {"name": "Timeless Encounters", "regions": "Around the world", "blurb": "A second global routing, weighted toward the ancient world."}, {"name": "African Wonders", "regions": "Africa", "blurb": "The continent's landscapes and wildlife, reached without a single commercial connection."}, {"name": "Asia Unveiled", "regions": "Asia", "blurb": "Imperial cities and island coastlines across the region."}, {"name": "New World Icons", "regions": "The Americas", "blurb": "North and South America's landmark places in one continuous journey."}, {"name": "Ancient Explorer", "regions": "Multi-continent", "blurb": "Built around the archaeological set-pieces of the old world."}, {"name": "International Intrigue", "regions": "Multi-continent", "blurb": "A routing that favours the harder-to-reach over the obvious."}, {"name": "Uncharted Discovery", "regions": "Multi-continent", "blurb": "The most remote routing the aircraft flies."}, {"name": "World of Adventures", "regions": "Multi-continent", "blurb": "Weighted toward active days rather than gallery days."}]$q$::jsonb,
  $q$[{"icon": "vip", "title": "Preferred Partner Recognition", "description": "Booked through us, your Four Seasons profile and preferences travel with you to every hotel on the routing."}, {"icon": "priority", "title": "Held Before General Release", "description": "Departures sell out on announcement. We register interest ahead of the public on-sale date."}, {"icon": "transfer", "title": "The Days Either Side", "description": "Pre- and post-journey stays booked under the same partner programmes as the rest of your travel."}, {"icon": "default", "title": "One Point of Contact", "description": "Deposits, documentation, insurance and the hundred small confirmations run through us, not through you."}]$q$::jsonb,
  null, $q$Published on request. Journeys are sold and operated by TCS World Travel.$q$, 10
),
(
  $q$abercrombie-kent$q$, $q$Abercrombie & Kent$q$, $q$safari$q$,
  $q$Life, well-travelled since 1962$q$,
  $q$Abercrombie & Kent invented the luxury safari and then spent sixty years extending the idea to every other continent. Today it runs private travel, small-group journeys, expedition cruises and its own private-jet programme, supported by more than 3,000 staff across 65 offices in 40 countries — including its own lodges and riverboats under A&K Sanctuary.$q$,
  $q${"eyebrow": "Guided Journeys", "heading": "The company that made the luxury safari, on all seven continents.", "body": "Founded by Geoffrey Kent in 1962, A&K's advantage is the ground operation: its own offices, its own guides, and its own properties in the places it sends you. That is what makes the difference between a well-booked trip and one where somebody is already waiting at the airstrip."}$q$::jsonb,
  $q$[{"name": "East & Southern Africa", "blurb": "The original territory, and still where A&K Sanctuary owns the most ground."}, {"name": "Antarctica & the Arctic", "blurb": "Expedition voyages at both poles, on purpose-built vessels."}, {"name": "Asia & the Subcontinent", "blurb": "Private travel through India, Japan, and Southeast Asia."}, {"name": "Egypt & the Nile", "blurb": "A&K's own riverboats on the stretch of river it has worked longest."}]$q$::jsonb,
  $q$[{"title": "A&K Sanctuary", "description": "Its own safari lodges and river vessels, rather than blocks bought from third parties."}, {"title": "Resident Guides", "description": "Local specialists on staff, not contracted per departure."}, {"title": "24/7 Ground Support", "description": "Offices in 40 countries mean somebody is awake and nearby when a plan changes."}, {"title": "A&K Philanthropy", "description": "Every booking funds conservation and community projects in the regions travelled."}, {"title": "Private Jet Programme", "description": "Seven-continent itineraries on a privately configured aircraft."}]$q$::jsonb,
  $q$[{"name": "Private Travel", "blurb": "A journey built from scratch around your dates, pace and interests."}, {"name": "Small Group Journeys", "blurb": "Guided departures capped low, for travellers who want the company."}, {"name": "Wildlife & Safari", "blurb": "The core programme — East and Southern Africa, on A&K's own ground."}, {"name": "Expedition Cruises", "blurb": "Polar and remote-coast voyages, including both poles."}, {"name": "Private Jet Journeys", "blurb": "All seven continents in a single continuous itinerary."}]$q$::jsonb,
  $q$[{"icon": "vip", "title": "Preferred Partner Booking", "description": "Your booking carries partner recognition with A&K rather than arriving as an anonymous reservation."}, {"icon": "priority", "title": "Space on Sold-Out Departures", "description": "We work the waitlist directly with A&K rather than through a public form."}, {"icon": "excursion", "title": "Itinerary Shaped Before You See It", "description": "We brief A&K on how you travel, so the first draft already fits."}, {"icon": "default", "title": "One Point of Contact", "description": "Deposits, documents and changes run through us for the length of the booking."}]$q$::jsonb,
  null, $q$Priced per itinerary on request.$q$, 20
),
(
  $q$micato-safaris$q$, $q$Micato Safaris$q$, $q$safari$q$,
  $q$Ten times the world's best safari outfitter$q$,
  $q$Micato Safaris is a family-run outfitter working East and Southern Africa and India, and a ten-time winner of Travel+Leisure's award for the world's best safari outfitter. Its journeys run 10 to 17 days, are almost entirely privately guided, and publish their prices — which for this category is unusual and makes planning considerably easier.$q$,
  $q${"eyebrow": "Safari", "heading": "The most-awarded outfitter in Africa, and a published price list.", "body": "Micato is small enough to be run by the family that founded it and long-established enough to hold relationships in Kenya and Tanzania that newer operators cannot. Its itineraries are fixed in shape but private in execution: your own guide, your own vehicle, your own pace."}$q$::jsonb,
  $q$[{"name": "Kenya & Tanzania", "blurb": "The core territory — the Mara, the Serengeti, and the migration between them."}, {"name": "South Africa, Botswana & Zambia", "blurb": "The southern circuit, from the Cape through the Okavango to the Falls."}, {"name": "Rwanda & Namibia", "blurb": "Gorilla tracking and the desert coast, added to longer routings."}, {"name": "India", "blurb": "A parallel programme through Rajasthan, the Ganges cities and the national parks."}]$q$::jsonb,
  $q$[{"title": "Privately Guided Throughout", "description": "Your own guide and vehicle rather than a shared game drive."}, {"title": "Family-Run Since 1966", "description": "The Pinto family still runs the company and the relationships behind it."}, {"title": "AmericaShare", "description": "Micato's own non-profit in Nairobi; each safari sold funds a child's education."}, {"title": "Door-to-Door Handling", "description": "Met on arrival and handed over at every transfer for the length of the trip."}]$q$::jsonb,
  $q$[{"name": "African Splendour", "days": 17, "regions": "South Africa, Kenya & Tanzania", "blurb": "The longest routing — three countries and the full range of landscape.", "price_from_usd": 45100}, {"name": "The Micato Grand Safari", "days": 15, "regions": "Kenya & Tanzania", "blurb": "The flagship East African itinerary.", "price_from_usd": 40150}, {"name": "East Africa's Golden Savannahs", "days": 15, "regions": "Kenya & Tanzania", "blurb": "Built around the great grass plains and the migration's timing.", "price_from_usd": 39750}, {"name": "Jewels of South Africa", "days": 13, "regions": "South Africa", "blurb": "Cape Town, the winelands and the private reserves.", "price_from_usd": 38900}, {"name": "Private Kenya Safari", "days": 13, "regions": "Kenya", "blurb": "Kenya alone, at depth rather than in survey.", "price_from_usd": 38650}, {"name": "The Great Herds of Kenya & Tanzania", "days": 13, "regions": "Kenya & Tanzania", "blurb": "Timed to the herds rather than to a fixed calendar.", "price_from_usd": 31750}, {"name": "The Hemingway Wing Safari", "days": 14, "regions": "Kenya & Tanzania", "blurb": "Light-aircraft transfers between camps, minimising road time.", "price_from_usd": 31450}, {"name": "Passage Through Botswana and Zimbabwe", "days": 14, "regions": "South Africa, Botswana, Zambia & Zimbabwe", "blurb": "The southern water systems and Victoria Falls.", "price_from_usd": 31400}, {"name": "Botswana's Timeless Wilderness", "days": 12, "regions": "South Africa, Botswana & Zambia", "blurb": "The Okavango and the Kalahari at the heart of it.", "price_from_usd": 27250}, {"name": "The Heart of Kenya & Tanzania", "days": 12, "regions": "Kenya & Tanzania", "blurb": "The shorter East African routing, without losing the essentials.", "price_from_usd": 25000}, {"name": "Tanzania Spectacular", "days": 10, "regions": "Tanzania", "blurb": "Tanzania alone — the Serengeti, the Crater, and the south.", "price_from_usd": 20700}, {"name": "The Soul of India", "days": 16, "regions": "India", "blurb": "Rajasthan, the Ganges, and the national parks.", "price_from_usd": 28450}, {"name": "Royal Palaces of India", "days": 16, "regions": "India", "blurb": "The palace route through Rajasthan.", "price_from_usd": 27900}, {"name": "Splendours of Northern India", "days": 13, "regions": "India", "blurb": "The northern circuit at a slightly shorter length.", "price_from_usd": 24850}]$q$::jsonb,
  $q$[{"icon": "vip", "title": "Preferred Partner Booking", "description": "Booked through us, your safari carries partner recognition with Micato from the first confirmation."}, {"icon": "priority", "title": "Camps Held in Migration Season", "description": "The camps worth having go a year out. We hold space while the dates are still moving."}, {"icon": "excursion", "title": "Itinerary Matched to the Herds", "description": "Which weeks, which camps, which direction the crossing runs — timing is most of the outcome."}, {"icon": "default", "title": "One Point of Contact", "description": "Deposits, documents, visas and flights run through us for the length of the booking."}]$q$::jsonb,
  20700, $q$Per person, from. Micato-published rates — verify current pricing before quoting.$q$, 21
)
on conflict (slug) do nothing;
