import { NextResponse } from 'next/server'
import { stripe, TIER_PRICES, FOUNDING_PRICES, type TierName, type FoundingTierName } from '@/lib/stripe'
import { getCurrentSuperAdmin } from '@/lib/admin-auth'

type BillingCycle = 'monthly' | 'annual'

export async function POST(request: Request) {
  try {
    const { tier, billingCycle = 'monthly', plan } = await request.json() as {
      tier: TierName
      billingCycle?: BillingCycle
      plan?: 'founding'
    }

    if (!TIER_PRICES[tier]) {
      return NextResponse.json({ error: 'Invalid tier' }, { status: 400 })
    }
    if (billingCycle !== 'monthly' && billingCycle !== 'annual') {
      return NextResponse.json({ error: 'Invalid billingCycle' }, { status: 400 })
    }

    // Build the origin from the request URL for redirect URLs
    const origin = new URL(request.url).origin

    // ── Founding Advisor (invitation-only beta) checkout ──────────────────
    // $0 setup, 30-day free trial, then the locked founding monthly rate. The
    // discount is the founding *price* itself (not a coupon), so it never
    // expires. See EAH_Beta_Launch_Build_Kit.md, Part A.
    if (plan === 'founding') {
      // Invitation-only. Founding checkout links may only be generated by a
      // signed-in super_admin from the admin console — never by an advisor or
      // an anonymous visitor. The standard (public) checkout branch below is
      // intentionally left unauthenticated for public self-serve signup.
      // This route is NOT covered by the middleware admin gate (the matcher
      // runs but only enforces auth on /admin/* and /agent-portal/*), so the
      // check must happen here.
      const admin = await getCurrentSuperAdmin()
      if (!admin) {
        return NextResponse.json(
          { error: 'Founding checkout is restricted to platform admins.' },
          { status: 403 },
        )
      }

      if (!(tier in FOUNDING_PRICES)) {
        return NextResponse.json(
          { error: 'Founding plan is not available for this tier' },
          { status: 400 },
        )
      }
      const founding = FOUNDING_PRICES[tier as FoundingTierName]
      const cohort = 'beta-1'

      const session = await stripe.checkout.sessions.create({
        mode: 'subscription',
        payment_method_types: ['card'],
        // Founding monthly price only — no setup-fee line item.
        line_items: [{ price: founding.monthly, quantity: 1 }],
        // Force card capture even though $0 is due today, so the subscription
        // auto-converts at the founding rate when the trial ends on day 30.
        payment_method_collection: 'always',
        subscription_data: {
          trial_period_days: 30,
          metadata: { tier, plan: 'founding', cohort },
        },
        // Mirror onto the session so the webhook's checkout.session.completed
        // handler can persist plan/cohort without retrieving the subscription.
        metadata: { tier, plan: 'founding', cohort },
        success_url: `${origin}/agent-portal/onboarding?session_id={CHECKOUT_SESSION_ID}&tier=${tier}`,
        cancel_url: `${origin}/#pricing`,
        // The deal is baked into the price — no promo codes.
        allow_promotion_codes: false,
      })

      return NextResponse.json({ url: session.url })
    }

    const prices = TIER_PRICES[tier]
    // Pick the recurring price for the requested cycle. Empty string means
    // the tier doesn't support that cycle (e.g. Agency on either, or any
    // future tier we add monthly-first).
    const recurringPriceId = billingCycle === 'annual' ? prices.annual : prices.monthly
    if (!recurringPriceId) {
      return NextResponse.json(
        { error: `${tier} tier is not available on ${billingCycle} billing.` },
        { status: 400 },
      )
    }

    // Business model v2 (docs/business-model-v2.md): the public base plan
    // (starter) runs a 30-day trial with no setup fee. Legacy tiers keep their
    // original behavior (setup fee on the first invoice, no trial).
    const withTrial = tier === 'starter'

    // Recurring subscription plus, when the tier still has one, the one-time
    // setup fee. Stripe supports mixing recurring + one-time line items in
    // 'subscription' mode; the setup fee lands on the first invoice only.
    const lineItems: { price: string; quantity: number }[] = [
      { price: recurringPriceId, quantity: 1 },
    ]
    if (prices.setup) {
      lineItems.push({ price: prices.setup, quantity: 1 })
    }

    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: lineItems,
      // Force card capture even when $0 is due today, so a trialing
      // subscription auto-converts on day 30.
      ...(withTrial ? { payment_method_collection: 'always' as const } : {}),
      subscription_data: {
        ...(withTrial ? { trial_period_days: 30 } : {}),
        metadata: {
          tier,
          billingCycle,
          ...(withTrial ? { trial: '30d' } : {}),
        },
      },
      metadata: {
        tier,
        billingCycle,
        ...(withTrial ? { trial: '30d' } : {}),
      },
      // After successful checkout, redirect to the onboarding wizard
      success_url: `${origin}/agent-portal/onboarding?session_id={CHECKOUT_SESSION_ID}&tier=${tier}`,
      cancel_url: `${origin}/#pricing`,
      // Allow promo codes
      allow_promotion_codes: true,
    })

    return NextResponse.json({ url: session.url })
  } catch (err: any) {
    console.error('Stripe checkout error:', err)
    return NextResponse.json({ error: err.message ?? 'Checkout failed' }, { status: 500 })
  }
}
