import { NextResponse } from 'next/server'
import { stripe, TIER_PRICES, FOUNDING_PRICES, type TierName, type FoundingTierName } from '@/lib/stripe'
import { getCurrentSuperAdmin } from '@/lib/admin-auth'

export async function POST(request: Request) {
  try {
    const { tier, plan } = await request.json() as { tier: TierName; plan?: 'founding' }

    if (!TIER_PRICES[tier]) {
      return NextResponse.json({ error: 'Invalid tier' }, { status: 400 })
    }

    // Build the origin from the request URL for redirect URLs
    const origin = new URL(request.url).origin

    // ── Founding Advisor (invitation-only beta) checkout ──────────────────
    // $0 setup, 90-day free trial, then the locked founding monthly rate. The
    // discount is the founding *price* itself (not a coupon), so it never
    // expires. See EAH_Beta_Launch_Build_Kit.md, Part A.
    if (plan === 'founding') {
      // Invitation-only. Founding checkout links may only be generated by a
      // signed-in super_admin from the admin console — never by an advisor or
      // an anonymous visitor. The standard (public) checkout branch below is
      // intentionally left unauthenticated for public self-serve signup.
      // This route is NOT covered by the middleware admin gate (the matcher
      // runs but only enforces auth on /admin/* and /agent-portal/*), so the
      // check must happen here.
      const admin = await getCurrentSuperAdmin()
      if (!admin) {
        return NextResponse.json(
          { error: 'Founding checkout is restricted to platform admins.' },
          { status: 403 },
        )
      }

      if (!(tier in FOUNDING_PRICES)) {
        return NextResponse.json(
          { error: 'Founding plan is not available for this tier' },
          { status: 400 },
        )
      }
      const founding = FOUNDING_PRICES[tier as FoundingTierName]
      const cohort = 'beta-1'

      const session = await stripe.checkout.sessions.create({
        mode: 'subscription',
        payment_method_types: ['card'],
        // Founding monthly price only — no setup-fee line item.
        line_items: [{ price: founding.monthly, quantity: 1 }],
        // Force card capture even though $0 is due today, so the subscription
        // auto-converts at the founding rate when the trial ends on day 90.
        payment_method_collection: 'always',
        subscription_data: {
          trial_period_days: 90,
          metadata: { tier, plan: 'founding', cohort },
        },
        // Mirror onto the session so the webhook's checkout.session.completed
        // handler can persist plan/cohort without retrieving the subscription.
        metadata: { tier, plan: 'founding', cohort },
        success_url: `${origin}/agent-portal/onboarding?session_id={CHECKOUT_SESSION_ID}&tier=${tier}`,
        cancel_url: `${origin}/#pricing`,
        // The deal is baked into the price — no promo codes.
        allow_promotion_codes: false,
      })

      return NextResponse.json({ url: session.url })
    }

    const prices = TIER_PRICES[tier]

    // Create Checkout session with both the recurring subscription AND one-time setup fee.
    // Stripe supports mixing recurring + one-time line items in 'subscription' mode.
    const session = await stripe.checkout.sessions.create({
      mode: 'subscription',
      payment_method_types: ['card'],
      line_items: [
        // Monthly recurring subscription
        {
          price: prices.monthly,
          quantity: 1,
        },
        // One-time setup fee — charged on the first invoice only
        {
          price: prices.setup,
          quantity: 1,
        },
      ],
      subscription_data: {
        metadata: {
          tier,
        },
      },
      metadata: {
        tier,
      },
      // After successful checkout, redirect to the onboarding wizard
      success_url: `${origin}/agent-portal/onboarding?session_id={CHECKOUT_SESSION_ID}&tier=${tier}`,
      cancel_url: `${origin}/#pricing`,
      // Allow promo codes
      allow_promotion_codes: true,
    })

    return NextResponse.json({ url: session.url })
  } catch (err: any) {
    console.error('Stripe checkout error:', err)
    return NextResponse.json({ error: err.message ?? 'Checkout failed' }, { status: 500 })
  }
}
